#basic
server:
  port: 9002
  
#log4j2
logging:
    config: classpath:log4j2.xml

#spring cloud
spring:
  cloud:
    gateway:
      routes:
          - id: rewritepath_route
            uri: lb://hic
            predicates:
            - Path=/hic/v1/**
            - Host=hic:9002
            filters:
            - StripPrefix=2
            - name: RequestRateLimiter
              args:
                request-rate-limiter.replenishRate: 1
                request-rate-limiter.burstCapacity: 1
                key-resolver: "#{@ipResolver}"
            #- RewritePath=/hic/(?<segment>.*), /$\{segment}

#eureka
eureka:
    client:
        serviceUrl:
            defaultZone: http://host.docker.internal:8001/eureka/
        healthcheck:
            enabled: true
    instance:
        prefer-ip-address: true

#ribbon
hic:
    ribbon:
        NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule
