#basic
server:
  port: 9000
  
#log4j2
logging:
    config: classpath:log4j2.xml

#spring cloud
spring:
  cloud:
    gateway:
      routes:
          - id: rewritepath_route
            uri: lb://hic
            predicates:
            - Path=/hic/v1/{segment}
            - Host=hic:9000
            filters:
            #- StripPrefix=2
            - SetPath=/{segment}
            #- RewritePath=/hic/(?<segment>.*), /$\{segment}

#eureka
eureka:
    client:
        serviceUrl:
            defaultZone: http://host.docker.internal:8001/eureka/
        healthcheck:
            enabled: true
    instance:
        prefer-ip-address: true
endpoints:
    shutdown:
        enabled: true
