#basic
server:
  port: 9000
  
#log4j2
logging:
    config: classpath:log4j2.xml

#spring cloud
spring:
  redis:
      port: 6379
      host: host.docker.internal
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 5s
      routes:
          - id: rewritepath_route
            uri: lb://hic
            predicates:
            - Path=/hic/v1/**
            - Host=hic:9000
            filters:
            - StripPrefix=2
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 2
                key-resolver: "#{@ipResolver}"
            #- RewritePath=/hic/(?<segment>.*), /$\{segment}

#eureka
eureka:
    client:
        serviceUrl:
            defaultZone: http://host.docker.internal:8001/eureka/
        healthcheck:
            enabled: true
    instance:
        prefer-ip-address: true

#ribbon
hic:
    ribbon:
        NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule
        


